#!/usr/bin/env bash
# install-hooks — put a shim in this repo's hooks directory that runs the
# checked-in hooks in scripts/git-hooks/.
#
#   npm run hooks:install
#
# It does NOT set core.hooksPath. This repo already has core.hooksPath set
# explicitly (to the absolute .git/hooks), that setting is shared by every
# worktree, and rewriting it from a script would change hook resolution for
# whatever else is running in a sibling worktree at the time. Instead we write
# into whatever directory git currently resolves — `git rev-parse --git-path
# hooks` honours core.hooksPath if it is set and falls back to the common
# .git/hooks if it is not.
#
# The shim is three lines and delegates to the repo copy, so it never needs
# reinstalling when a hook changes, and a checkout of an older commit that has
# no scripts/git-hooks/ simply no-ops instead of blocking commits.
#
# It VERIFIES afterwards, and says so. A setting that is quietly ignored is the
# failure this repo already paid for once (worktree.bgIsolation, set to a value
# that did not exist, silently doing nothing for a day) — an installer that
# prints "installed" without checking is the same bug in a different costume.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$(git rev-parse --git-path hooks)"
case "$HOOK_DIR" in
  /*) ;;
  *) HOOK_DIR="$ROOT/$HOOK_DIR" ;;
esac

mkdir -p "$HOOK_DIR"

installed=0
for src in "$ROOT"/scripts/git-hooks/*; do
  [ -f "$src" ] || continue
  name="$(basename "$src")"
  dest="$HOOK_DIR/$name"
  cat > "$dest" <<'SHIM'
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — do not edit. The real hook is
# scripts/git-hooks/<name> in the working tree; this only delegates to it.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
HOOK="$ROOT/scripts/git-hooks/$(basename "$0")"
[ -x "$HOOK" ] || exit 0
exec "$HOOK" "$@"
SHIM
  chmod +x "$dest"
  installed=$((installed + 1))
done

echo "install-hooks: wrote $installed shim(s) to $HOOK_DIR"

# --- verify, don't assume ---------------------------------------------------
fail=0
for src in "$ROOT"/scripts/git-hooks/*; do
  [ -f "$src" ] || continue
  name="$(basename "$src")"
  if [ ! -x "$src" ]; then
    echo "install-hooks: FAIL scripts/git-hooks/$name is not executable (chmod +x it and commit the mode)." >&2
    fail=1
  fi
  if [ ! -x "$HOOK_DIR/$name" ]; then
    echo "install-hooks: FAIL $HOOK_DIR/$name is missing or not executable." >&2
    fail=1
  fi
done

if [ "$fail" -ne 0 ]; then
  exit 1
fi

echo "install-hooks: verified. Hooks resolve to $HOOK_DIR"

# --- post-checkout needs a SHARED hooks dir, so check it is one -------------
#
# The checks above prove the shim exists and is executable. For post-checkout
# that is not enough to prove it will ever RUN, because it has to fire inside a
# worktree that does not exist yet.
#
# git resolves hooks from core.hooksPath when it is set, and from
# $GIT_COMMON_DIR/hooks when it is not. Both are shared by every worktree — but
# only if core.hooksPath is ABSOLUTE. Set to a relative path, git resolves it
# against each working tree's own root, so a brand-new worktree would look in
# its own empty directory and post-checkout would silently never fire. The
# install would still print "verified": installed, checked, dead. That is the
# same bug in a different costume this file's header is about, so it gets a
# check rather than a sentence.
#
# Not a hard failure: commit-msg and pre-commit install correctly in that
# setup, and refusing the whole install to complain about one hook would be
# worse than saying so loudly.
if [ -f "$ROOT/scripts/git-hooks/post-checkout" ]; then
  configured="$(git config --get core.hooksPath || true)"
  if [ -n "$configured" ]; then
    case "$configured" in
      /*) ;;
      *)
        echo "install-hooks: WARNING — core.hooksPath is set to a RELATIVE path" >&2
        echo "               ('$configured'). git resolves that against each working" >&2
        echo "               tree's own root, so a new worktree will look in its own" >&2
        echo "               empty directory and the post-checkout hook will NOT fire" >&2
        echo "               for 'git worktree add'. node_modules and planning-docs" >&2
        echo "               will not be linked. Fix: set it to an absolute path," >&2
        echo "               or unset it so hooks come from the shared .git/hooks." >&2
        ;;
    esac
  fi
fi

echo "install-hooks: note — hooks are per-clone and per-worktree. Anyone who"
echo "               never runs this has no hook; the CI job 'changelog' is the"
echo "               enforcement that lives in the repo."
